'use client'
import { SearchParamsContext } from "next/dist/shared/lib/hooks-client-context.shared-runtime";
import Image from "next/image";
import { useState } from "react";



const RenderCards = ({data, title}){
  if(data?.length > 0) return data.map((post) => <Card key={post._id} {...post} />)
}
export default function Home() {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);
  const [searchText, setSearchText] = useState(null);
  

  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1>The Community  Showcase</h1>
        <p>Browse through a collection of imaginative an visually stunning images generated by Dall-E Ai</p>
      </div>
      <div className="mt-16">
        <FormField />

      </div>
      <div className="mt-10">
        {loading ? (
          <div className="flex justify-center items-center">
            <Loader />
          </div>
        ):(
          <>
          {searchText && (
            <h2 className="text-[#222328]">
              Showing results for  <span>{searchText}</span>
            </h2>
          )}
          <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">


          </div>
          </>
        )}
      </div>
    </section>
  );
}
